add install script

diff --git a/root/etc/s6-overlay/s6-rc.d/init-openssh-server-config/run b/root/etc/s6-overlay/s6-rc.d/init-openssh-server-config/run
--- a/root/etc/s6-overlay/s6-rc.d/init-openssh-server-config/run
+++ b/root/etc/s6-overlay/s6-rc.d/init-openssh-server-config/run
@@ -22,6 +22,29 @@ else
     echo "sudo is disabled."
 fi
 
+# Check if the INSTALL_SCRIPT_URL environment variable is set
+if [[ -n "${INSTALL_SCRIPT_URL}" ]]; then
+    echo "Downloading script from ${INSTALL_SCRIPT_URL}..."
+    
+    # Download the script
+    curl -s -o /tmp/install_script.sh "${INSTALL_SCRIPT_URL}"
+    
+    # Check if the download was successful
+    if [[ $? -eq 0 ]]; then
+        echo "Download successful. Running the script..."
+        
+        # Make the script executable and run it
+        chmod +x /tmp/install_script.sh
+        bash /tmp/install_script.sh
+        
+        rm /tmp/install_script.sh
+    else
+        echo "Failed to download the script."
+    fi
+else
+    echo "Environment variable INSTALL_SCRIPT_URL is not set."
+fi
+
 MOTD_FILE="/etc/motd"
 
 # Check if WELCOME_MESSAGE is set and not empty
